### ISSUE TITLE
Getting flagged as malware

### ISSUE THREAD

**Issue by kayky21** [xntkrnl/UsefulZapGun#1]
Microsoft Defender
Trojan:Script/Wacatac.B!ml

file: C:\Users\kayky21\Downloads\ujiomborsh-Useful_Zap_Gun-0.0.2.zip
webfile: C:\Users\kayky21\Downloads\ujiomborsh-Useful_Zap_Gun-0.0.2.zip|https://gcdn.thunderstore.io/live/repository/packages/mborsh-Useful_Zap_Gun-0.0.2.zip|pid:14668,ProcessStart:133775822923894862

wtf???????

**Comment by xntkrnl** [comment]
Hi, thanks for your feedback.
Truly wtf moment
I always knew that windows defender would protect someone from my mods

https://www.virustotal.com/gui/file/33dbfe9e8b901621445f4e6ed5c418f2585cf461b974af3d1bac8390fa74c245
https://www.virustotal.com/gui/url/51f01b9dc8e2ac0640f678fce7575632e4d501ebb6e054d3fd9631faae43af70

**Comment by xntkrnl** [comment]
I haven't received a single similar message in 24 hours, and people on the modding server also said that this sometimes happened with other mods (rarely), so I'm closing this issue until another similar one appears from another person.

In short: **false positive**, which you can see for yourself thanks to the virustotal scans above
